[FILE_SETTINGS]
DIR_INPUT = input/
DIR_OUTPUT = output/
DIR_FIGURES = output/figures/
DEM_FILENAME = dem_gee.tif
GPKG_NAME = catchment_data.gpkg
CATCHMENT_FILENAME = catchment_mghydro.geojson
RIVERS_FILENAME = catchment_mghydro_rivers.geojson

[CONFIG]
GEE_BACKEND = webservice
; gee
CLOUD_PROJECT = matilda-edu
COORDS = [42.300264, 78.091444]
; Kyzylsuu
CATCHMENT_BACKEND = mghydro
MGHYDRO_PRECISION = high
CALIBRATION_PERIOD = ['1998-01-01', '2020-12-31']
DEM = ['Image', 'MERIT/DEM/v1_0_3','dem', 'MERIT 30m']
GEE_DOWNLOAD_XR = True
PROJECTIONS = True
SHOW_MAP = True
PLOT_STYLE = ['science','no-latex']
COMPACT_FILES = False
NUM_CORES = 4
ZIP_OUTPUT = True
