[GOOGLE]
PUBLIC_CLOUD_PROJECT = matilda-online-public
TIMEOUT = 300
BASE_URL = https://matilda-gee-data-webservice-1065748087920.europe-west1.run.app
;PUBLIC_API_KEY =


[HU]
MEDIA_API_URL = https://rs.cms.hu-berlin.de/matilda/api/?
MEDIA_PRIVATE_KEY = 9a19c0cee1cde5fe9180c31c27a8145bc6f7a110cfaa3806ba262eb63d16f086
MEDIA_USER = gast

